b=22459 Unused variables
i=ricardo.m.correia

Unused variable 'waited' in filter_fini()
Unused variable 'usource_len' in mount_lustre.c main()
Unused variable 'dt_obj' in fld_index_create()
Unused label 'out' in mdd_declare_setattr_log()

cc1: warnings being treated as errors
~src/git/lustre/lustre/fld/fld_index.c: In function ‘fld_index_create’:
~src/git/lustre/lustre/fld/fld_index.c:181: error: unused variable ‘dt_obj’